"""
CPython 3.13 bytecode opcodes
"""

import xdis.opcodes.opcode_313 as opcode_313
from xdis.opcodes.base import def_op, finalize_opcodes, init_opdata, rm_op, update_pj3

version_tuple = (3, 14)
python_implementation = "CPython"

loc = locals()

init_opdata(loc, opcode_313, version_tuple)

"""
ops in order
ops_313 = ['CACHE', 'BEFORE_ASYNC_WITH', 'BEFORE_WITH', '<3>', 'BINARY_SLICE', 'BINARY_SUBSCR', 'CHECK_EG_MATCH', 'CHECK_EXC_MATCH', 'CLEANUP_THROW', 'DELETE_SUBSCR', 'END_ASYNC_FOR', 'END_FOR', 'END_SEND', 'EXIT_INIT_CHECK', 'FORMAT_SIMPLE', 'FORMAT_WITH_SPEC', 'GET_AITER', 'RESERVED', 'GET_ANEXT', 'GET_ITER', 'GET_LEN', 'GET_YIELD_FROM_ITER', 'INTERPRETER_EXIT', 'LOAD_ASSERTION_ERROR', 'LOAD_BUILD_CLASS', 'LOAD_LOCALS', 'MAKE_FUNCTION', 'MATCH_KEYS', 'MATCH_MAPPING', 'MATCH_SEQUENCE', 'NOP', 'POP_EXCEPT', 'POP_TOP', 'PUSH_EXC_INFO', 'PUSH_NULL', 'RETURN_GENERATOR', 'RETURN_VALUE', 'SETUP_ANNOTATIONS', 'STORE_SLICE', 'STORE_SUBSCR', 'TO_BOOL', 'UNARY_INVERT', 'UNARY_NEGATIVE', 'UNARY_NOT', 'WITH_EXCEPT_START', 'BINARY_OP', 'BUILD_CONST_KEY_MAP', 'BUILD_LIST', 'BUILD_MAP', 'BUILD_SET', 'BUILD_SLICE', 'BUILD_STRING', 'BUILD_TUPLE', 'CALL', 'CALL_FUNCTION_EX', 'CALL_INTRINSIC_1', 'CALL_INTRINSIC_2', 'CALL_KW', 'COMPARE_OP', 'CONTAINS_OP', 'CONVERT_VALUE', 'COPY', 'COPY_FREE_VARS', 'DELETE_ATTR', 'DELETE_DEREF', 'DELETE_FAST', 'DELETE_GLOBAL', 'DELETE_NAME', 'DICT_MERGE', 'DICT_UPDATE', 'ENTER_EXECUTOR', 'EXTENDED_ARG', 'FOR_ITER', 'GET_AWAITABLE', 'IMPORT_FROM', 'IMPORT_NAME', 'IS_OP', 'JUMP_BACKWARD', 'JUMP_BACKWARD_NO_INTERRUPT', 'JUMP_FORWARD', 'LIST_APPEND', 'LIST_EXTEND', 'LOAD_ATTR', 'LOAD_CONST', 'LOAD_DEREF', 'LOAD_FAST', 'LOAD_FAST_AND_CLEAR', 'LOAD_FAST_CHECK', 'LOAD_FAST_LOAD_FAST', 'LOAD_FROM_DICT_OR_DEREF', 'LOAD_FROM_DICT_OR_GLOBALS', 'LOAD_GLOBAL', 'LOAD_NAME', 'LOAD_SUPER_ATTR', 'MAKE_CELL', 'MAP_ADD', 'MATCH_CLASS', 'POP_JUMP_IF_FALSE', 'POP_JUMP_IF_NONE', 'POP_JUMP_IF_NOT_NONE', 'POP_JUMP_IF_TRUE', 'RAISE_VARARGS', 'RERAISE', 'RETURN_CONST', 'SEND', 'SET_ADD', 'SET_FUNCTION_ATTRIBUTE', 'SET_UPDATE', 'STORE_ATTR', 'STORE_DEREF', 'STORE_FAST', 'STORE_FAST_LOAD_FAST', 'STORE_FAST_STORE_FAST', 'STORE_GLOBAL', 'STORE_NAME', 'SWAP', 'UNPACK_EX', 'UNPACK_SEQUENCE', 'YIELD_VALUE', '<119>', '<120>', '<121>', '<122>', '<123>', '<124>', '<125>', '<126>', '<127>', '<128>', '<129>', '<130>', '<131>', '<132>', '<133>', '<134>', '<135>', '<136>', '<137>', '<138>', '<139>', '<140>', '<141>', '<142>', '<143>', '<144>', '<145>', '<146>', '<147>', '<148>', 'RESUME', '<150>', '<151>', '<152>', '<153>', '<154>', '<155>', '<156>', '<157>', '<158>', '<159>', '<160>', '<161>', '<162>', '<163>', '<164>', '<165>', '<166>', '<167>', '<168>', '<169>', '<170>', '<171>', '<172>', '<173>', '<174>', '<175>', '<176>', '<177>', '<178>', '<179>', '<180>', '<181>', '<182>', '<183>', '<184>', '<185>', '<186>', '<187>', '<188>', '<189>', '<190>', '<191>', '<192>', '<193>', '<194>', '<195>', '<196>', '<197>', '<198>', '<199>', '<200>', '<201>', '<202>', '<203>', '<204>', '<205>', '<206>', '<207>', '<208>', '<209>', '<210>', '<211>', '<212>', '<213>', '<214>', '<215>', '<216>', '<217>', '<218>', '<219>', '<220>', '<221>', '<222>', '<223>', '<224>', '<225>', '<226>', '<227>', '<228>', '<229>', '<230>', '<231>', '<232>', '<233>', '<234>', '<235>', 'INSTRUMENTED_RESUME', 'INSTRUMENTED_END_FOR', 'INSTRUMENTED_END_SEND', 'INSTRUMENTED_RETURN_VALUE', 'INSTRUMENTED_RETURN_CONST', 'INSTRUMENTED_YIELD_VALUE', 'INSTRUMENTED_LOAD_SUPER_ATTR', 'INSTRUMENTED_FOR_ITER', 'INSTRUMENTED_CALL', 'INSTRUMENTED_CALL_KW', 'INSTRUMENTED_CALL_FUNCTION_EX', 'INSTRUMENTED_INSTRUCTION', 'INSTRUMENTED_JUMP_FORWARD', 'INSTRUMENTED_JUMP_BACKWARD', 'INSTRUMENTED_POP_JUMP_IF_TRUE', 'INSTRUMENTED_POP_JUMP_IF_FALSE', 'INSTRUMENTED_POP_JUMP_IF_NONE', 'INSTRUMENTED_POP_JUMP_IF_NOT_NONE', 'INSTRUMENTED_LINE', '<255>', 'JUMP', 'JUMP_NO_INTERRUPT', 'LOAD_CLOSURE', 'LOAD_METHOD', 'LOAD_SUPER_METHOD', 'LOAD_ZERO_SUPER_ATTR', 'LOAD_ZERO_SUPER_METHOD', 'POP_BLOCK', 'SETUP_CLEANUP', 'SETUP_FINALLY', 'SETUP_WITH', 'STORE_FAST_MAYBE_NULL']
ops_314 = ['CACHE', 'BINARY_SLICE', 'BUILD_TEMPLATE', 'BINARY_OP_INPLACE_ADD_UNICODE', 'CALL_FUNCTION_EX', 'CHECK_EG_MATCH', 'CHECK_EXC_MATCH', 'CLEANUP_THROW', 'DELETE_SUBSCR', 'END_FOR', 'END_SEND', 'EXIT_INIT_CHECK', 'FORMAT_SIMPLE', 'FORMAT_WITH_SPEC', 'GET_AITER', 'GET_ANEXT', 'GET_ITER', 'RESERVED', 'GET_LEN', 'GET_YIELD_FROM_ITER', 'INTERPRETER_EXIT', 'LOAD_BUILD_CLASS', 'LOAD_LOCALS', 'MAKE_FUNCTION', 'MATCH_KEYS', 'MATCH_MAPPING', 'MATCH_SEQUENCE', 'NOP', 'NOT_TAKEN', 'POP_EXCEPT', 'POP_ITER', 'POP_TOP', 'PUSH_EXC_INFO', 'PUSH_NULL', 'RETURN_GENERATOR', 'RETURN_VALUE', 'SETUP_ANNOTATIONS', 'STORE_SLICE', 'STORE_SUBSCR', 'TO_BOOL', 'UNARY_INVERT', 'UNARY_NEGATIVE', 'UNARY_NOT', 'WITH_EXCEPT_START', 'BINARY_OP', 'BUILD_INTERPOLATION', 'BUILD_LIST', 'BUILD_MAP', 'BUILD_SET', 'BUILD_SLICE', 'BUILD_STRING', 'BUILD_TUPLE', 'CALL', 'CALL_INTRINSIC_1', 'CALL_INTRINSIC_2', 'CALL_KW', 'COMPARE_OP', 'CONTAINS_OP', 'CONVERT_VALUE', 'COPY', 'COPY_FREE_VARS', 'DELETE_ATTR', 'DELETE_DEREF', 'DELETE_FAST', 'DELETE_GLOBAL', 'DELETE_NAME', 'DICT_MERGE', 'DICT_UPDATE', 'END_ASYNC_FOR', 'EXTENDED_ARG', 'FOR_ITER', 'GET_AWAITABLE', 'IMPORT_FROM', 'IMPORT_NAME', 'IS_OP', 'JUMP_BACKWARD', 'JUMP_BACKWARD_NO_INTERRUPT', 'JUMP_FORWARD', 'LIST_APPEND', 'LIST_EXTEND', 'LOAD_ATTR', 'LOAD_COMMON_CONSTANT', 'LOAD_CONST', 'LOAD_DEREF', 'LOAD_FAST', 'LOAD_FAST_AND_CLEAR', 'LOAD_FAST_BORROW', 'LOAD_FAST_BORROW_LOAD_FAST_BORROW', 'LOAD_FAST_CHECK', 'LOAD_FAST_LOAD_FAST', 'LOAD_FROM_DICT_OR_DEREF', 'LOAD_FROM_DICT_OR_GLOBALS', 'LOAD_GLOBAL', 'LOAD_NAME', 'LOAD_SMALL_INT', 'LOAD_SPECIAL', 'LOAD_SUPER_ATTR', 'MAKE_CELL', 'MAP_ADD', 'MATCH_CLASS', 'POP_JUMP_IF_FALSE', 'POP_JUMP_IF_NONE', 'POP_JUMP_IF_NOT_NONE', 'POP_JUMP_IF_TRUE', 'RAISE_VARARGS', 'RERAISE', 'SEND', 'SET_ADD', 'SET_FUNCTION_ATTRIBUTE', 'SET_UPDATE', 'STORE_ATTR', 'STORE_DEREF', 'STORE_FAST', 'STORE_FAST_LOAD_FAST', 'STORE_FAST_STORE_FAST', 'STORE_GLOBAL', 'STORE_NAME', 'SWAP', 'UNPACK_EX', 'UNPACK_SEQUENCE', 'YIELD_VALUE', '<121>', '<122>', '<123>', '<124>', '<125>', '<126>', '<127>', 'RESUME', 'BINARY_OP_ADD_FLOAT', 'BINARY_OP_ADD_INT', 'BINARY_OP_ADD_UNICODE', 'BINARY_OP_EXTEND', 'BINARY_OP_MULTIPLY_FLOAT', 'BINARY_OP_MULTIPLY_INT', 'BINARY_OP_SUBSCR_DICT', 'BINARY_OP_SUBSCR_GETITEM', 'BINARY_OP_SUBSCR_LIST_INT', 'BINARY_OP_SUBSCR_LIST_SLICE', 'BINARY_OP_SUBSCR_STR_INT', 'BINARY_OP_SUBSCR_TUPLE_INT', 'BINARY_OP_SUBTRACT_FLOAT', 'BINARY_OP_SUBTRACT_INT', 'CALL_ALLOC_AND_ENTER_INIT', 'CALL_BOUND_METHOD_EXACT_ARGS', 'CALL_BOUND_METHOD_GENERAL', 'CALL_BUILTIN_CLASS', 'CALL_BUILTIN_FAST', 'CALL_BUILTIN_FAST_WITH_KEYWORDS', 'CALL_BUILTIN_O', 'CALL_ISINSTANCE', 'CALL_KW_BOUND_METHOD', 'CALL_KW_NON_PY', 'CALL_KW_PY', 'CALL_LEN', 'CALL_LIST_APPEND', 'CALL_METHOD_DESCRIPTOR_FAST', 'CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS', 'CALL_METHOD_DESCRIPTOR_NOARGS', 'CALL_METHOD_DESCRIPTOR_O', 'CALL_NON_PY_GENERAL', 'CALL_PY_EXACT_ARGS', 'CALL_PY_GENERAL', 'CALL_STR_1', 'CALL_TUPLE_1', 'CALL_TYPE_1', 'COMPARE_OP_FLOAT', 'COMPARE_OP_INT', 'COMPARE_OP_STR', 'CONTAINS_OP_DICT', 'CONTAINS_OP_SET', 'FOR_ITER_GEN', 'FOR_ITER_LIST', 'FOR_ITER_RANGE', 'FOR_ITER_TUPLE', 'JUMP_BACKWARD_JIT', 'JUMP_BACKWARD_NO_JIT', 'LOAD_ATTR_CLASS', 'LOAD_ATTR_CLASS_WITH_METACLASS_CHECK', 'LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN', 'LOAD_ATTR_INSTANCE_VALUE', 'LOAD_ATTR_METHOD_LAZY_DICT', 'LOAD_ATTR_METHOD_NO_DICT', 'LOAD_ATTR_METHOD_WITH_VALUES', 'LOAD_ATTR_MODULE', 'LOAD_ATTR_NONDESCRIPTOR_NO_DICT', 'LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES', 'LOAD_ATTR_PROPERTY', 'LOAD_ATTR_SLOT', 'LOAD_ATTR_WITH_HINT', 'LOAD_CONST_IMMORTAL', 'LOAD_CONST_MORTAL', 'LOAD_GLOBAL_BUILTIN', 'LOAD_GLOBAL_MODULE', 'LOAD_SUPER_ATTR_ATTR', 'LOAD_SUPER_ATTR_METHOD', 'RESUME_CHECK', 'SEND_GEN', 'STORE_ATTR_INSTANCE_VALUE', 'STORE_ATTR_SLOT', 'STORE_ATTR_WITH_HINT', 'STORE_SUBSCR_DICT', 'STORE_SUBSCR_LIST_INT', 'TO_BOOL_ALWAYS_TRUE', 'TO_BOOL_BOOL', 'TO_BOOL_INT', 'TO_BOOL_LIST', 'TO_BOOL_NONE', 'TO_BOOL_STR', 'UNPACK_SEQUENCE_LIST', 'UNPACK_SEQUENCE_TUPLE', 'UNPACK_SEQUENCE_TWO_TUPLE', '<212>', '<213>', '<214>', '<215>', '<216>', '<217>', '<218>', '<219>', '<220>', '<221>', '<222>', '<223>', '<224>', '<225>', '<226>', '<227>', '<228>', '<229>', '<230>', '<231>', '<232>', '<233>', 'INSTRUMENTED_END_FOR', 'INSTRUMENTED_POP_ITER', 'INSTRUMENTED_END_SEND', 'INSTRUMENTED_FOR_ITER', 'INSTRUMENTED_INSTRUCTION', 'INSTRUMENTED_JUMP_FORWARD', 'INSTRUMENTED_NOT_TAKEN', 'INSTRUMENTED_POP_JUMP_IF_TRUE', 'INSTRUMENTED_POP_JUMP_IF_FALSE', 'INSTRUMENTED_POP_JUMP_IF_NONE', 'INSTRUMENTED_POP_JUMP_IF_NOT_NONE', 'INSTRUMENTED_RESUME', 'INSTRUMENTED_RETURN_VALUE', 'INSTRUMENTED_YIELD_VALUE', 'INSTRUMENTED_END_ASYNC_FOR', 'INSTRUMENTED_LOAD_SUPER_ATTR', 'INSTRUMENTED_CALL', 'INSTRUMENTED_CALL_KW', 'INSTRUMENTED_CALL_FUNCTION_EX', 'INSTRUMENTED_JUMP_BACKWARD', 'INSTRUMENTED_LINE', 'ENTER_EXECUTOR', 'ANNOTATIONS_PLACEHOLDER', 'JUMP', 'JUMP_IF_FALSE', 'JUMP_IF_TRUE', 'JUMP_NO_INTERRUPT', 'LOAD_CLOSURE', 'POP_BLOCK', 'SETUP_CLEANUP', 'SETUP_FINALLY', 'SETUP_WITH', 'STORE_FAST_MAYBE_NULL']

ops that stayed the same
[(0, ('CACHE', 'CACHE')), (17, ('RESERVED', 'RESERVED')), (254, ('INSTRUMENTED_LINE', 'INSTRUMENTED_LINE'))]

op    opname 3.13                           opname 3.14
-------------------------------------------------------
(0,   ('CACHE',                             'CACHE')),
(1,   ('BEFORE_ASYNC_WITH',                 'BINARY_SLICE')),
(2,   ('BEFORE_WITH',                       'BUILD_TEMPLATE')),
(3,   ('<3>',                               'BINARY_OP_INPLACE_ADD_UNICODE')),
(4,   ('BINARY_SLICE',                      'CALL_FUNCTION_EX')),
(5,   ('BINARY_SUBSCR',                     'CHECK_EG_MATCH')),
(6,   ('CHECK_EG_MATCH',                    'CHECK_EXC_MATCH')),
(7,   ('CHECK_EXC_MATCH',                   'CLEANUP_THROW')),
(8,   ('CLEANUP_THROW',                     'DELETE_SUBSCR')),
(9,   ('DELETE_SUBSCR',                     'END_FOR')),
(10,  ('END_ASYNC_FOR',                     'END_SEND')),
(11,  ('END_FOR',                           'EXIT_INIT_CHECK')),
(12,  ('END_SEND',                          'FORMAT_SIMPLE')),
(13,  ('EXIT_INIT_CHECK',                   'FORMAT_WITH_SPEC')),
(14,  ('FORMAT_SIMPLE',                     'GET_AITER')),
(15,  ('FORMAT_WITH_SPEC',                  'GET_ANEXT')),
(16,  ('GET_AITER',                         'GET_ITER')),
(17,  ('RESERVED',                          'RESERVED')),
(18,  ('GET_ANEXT',                         'GET_LEN')),
(19,  ('GET_ITER',                          'GET_YIELD_FROM_ITER')),
(20,  ('GET_LEN',                           'INTERPRETER_EXIT')),
(21,  ('GET_YIELD_FROM_ITER',               'LOAD_BUILD_CLASS')),
(22,  ('INTERPRETER_EXIT',                  'LOAD_LOCALS')),
(23,  ('LOAD_ASSERTION_ERROR',              'MAKE_FUNCTION')),
(24,  ('LOAD_BUILD_CLASS',                  'MATCH_KEYS')),
(25,  ('LOAD_LOCALS',                       'MATCH_MAPPING')),
(26,  ('MAKE_FUNCTION',                     'MATCH_SEQUENCE')),
(27,  ('MATCH_KEYS',                        'NOP')),
(28,  ('MATCH_MAPPING',                     'NOT_TAKEN')),
(29,  ('MATCH_SEQUENCE',                    'POP_EXCEPT')),
(30,  ('NOP',                               'POP_ITER')),
(31,  ('POP_EXCEPT',                        'POP_TOP')),
(32,  ('POP_TOP',                           'PUSH_EXC_INFO')),
(33,  ('PUSH_EXC_INFO',                     'PUSH_NULL')),
(34,  ('PUSH_NULL',                         'RETURN_GENERATOR')),
(35,  ('RETURN_GENERATOR',                  'RETURN_VALUE')),
(36,  ('RETURN_VALUE',                      'SETUP_ANNOTATIONS')),
(37,  ('SETUP_ANNOTATIONS',                 'STORE_SLICE')),
(38,  ('STORE_SLICE',                       'STORE_SUBSCR')),
(39,  ('STORE_SUBSCR',                      'TO_BOOL')),
(40,  ('TO_BOOL',                           'UNARY_INVERT')),
(41,  ('UNARY_INVERT',                      'UNARY_NEGATIVE')),
(42,  ('UNARY_NEGATIVE',                    'UNARY_NOT')),
(43,  ('UNARY_NOT',                         'WITH_EXCEPT_START')),
(44,  ('WITH_EXCEPT_START',                 'BINARY_OP')),
(45,  ('BINARY_OP',                         'BUILD_INTERPOLATION')),
(46,  ('BUILD_CONST_KEY_MAP',               'BUILD_LIST')),
(47,  ('BUILD_LIST',                        'BUILD_MAP')),
(48,  ('BUILD_MAP',                         'BUILD_SET')),
(49,  ('BUILD_SET',                         'BUILD_SLICE')),
(50,  ('BUILD_SLICE',                       'BUILD_STRING')),
(51,  ('BUILD_STRING',                      'BUILD_TUPLE')),
(52,  ('BUILD_TUPLE',                       'CALL')),
(53,  ('CALL',                              'CALL_INTRINSIC_1')),
(54,  ('CALL_FUNCTION_EX',                  'CALL_INTRINSIC_2')),
(55,  ('CALL_INTRINSIC_1',                  'CALL_KW')),
(56,  ('CALL_INTRINSIC_2',                  'COMPARE_OP')),
(57,  ('CALL_KW',                           'CONTAINS_OP')),
(58,  ('COMPARE_OP',                        'CONVERT_VALUE')),
(59,  ('CONTAINS_OP',                       'COPY')),
(60,  ('CONVERT_VALUE',                     'COPY_FREE_VARS')),
(61,  ('COPY',                              'DELETE_ATTR')),
(62,  ('COPY_FREE_VARS',                    'DELETE_DEREF')),
(63,  ('DELETE_ATTR',                       'DELETE_FAST')),
(64,  ('DELETE_DEREF',                      'DELETE_GLOBAL')),
(65,  ('DELETE_FAST',                       'DELETE_NAME')),
(66,  ('DELETE_GLOBAL',                     'DICT_MERGE')),
(67,  ('DELETE_NAME',                       'DICT_UPDATE')),
(68,  ('DICT_MERGE',                        'END_ASYNC_FOR')),
(69,  ('DICT_UPDATE',                       'EXTENDED_ARG')),
(70,  ('ENTER_EXECUTOR',                    'FOR_ITER')),
(71,  ('EXTENDED_ARG',                      'GET_AWAITABLE')),
(72,  ('FOR_ITER',                          'IMPORT_FROM')),
(73,  ('GET_AWAITABLE',                     'IMPORT_NAME')),
(74,  ('IMPORT_FROM',                       'IS_OP')),
(75,  ('IMPORT_NAME',                       'JUMP_BACKWARD')),
(76,  ('IS_OP',                             'JUMP_BACKWARD_NO_INTERRUPT')),
(77,  ('JUMP_BACKWARD',                     'JUMP_FORWARD')),
(78,  ('JUMP_BACKWARD_NO_INTERRUPT',        'LIST_APPEND')),
(79,  ('JUMP_FORWARD',                      'LIST_EXTEND')),
(80,  ('LIST_APPEND',                       'LOAD_ATTR')),
(81,  ('LIST_EXTEND',                       'LOAD_COMMON_CONSTANT')),
(82,  ('LOAD_ATTR',                         'LOAD_CONST')),
(83,  ('LOAD_CONST',                        'LOAD_DEREF')),
(84,  ('LOAD_DEREF',                        'LOAD_FAST')),
(85,  ('LOAD_FAST',                         'LOAD_FAST_AND_CLEAR')),
(86,  ('LOAD_FAST_AND_CLEAR',               'LOAD_FAST_BORROW')),
(87,  ('LOAD_FAST_CHECK',                   'LOAD_FAST_BORROW_LOAD_FAST_BORROW')),
(88,  ('LOAD_FAST_LOAD_FAST',               'LOAD_FAST_CHECK')),
(89,  ('LOAD_FROM_DICT_OR_DEREF',           'LOAD_FAST_LOAD_FAST')),
(90,  ('LOAD_FROM_DICT_OR_GLOBALS',         'LOAD_FROM_DICT_OR_DEREF')),
(91,  ('LOAD_GLOBAL',                       'LOAD_FROM_DICT_OR_GLOBALS')),
(92,  ('LOAD_NAME',                         'LOAD_GLOBAL')),
(93,  ('LOAD_SUPER_ATTR',                   'LOAD_NAME')),
(94,  ('MAKE_CELL',                         'LOAD_SMALL_INT')),
(95,  ('MAP_ADD',                           'LOAD_SPECIAL')),
(96,  ('MATCH_CLASS',                       'LOAD_SUPER_ATTR')),
(97,  ('POP_JUMP_IF_FALSE',                 'MAKE_CELL')),
(98,  ('POP_JUMP_IF_NONE',                  'MAP_ADD')),
(99,  ('POP_JUMP_IF_NOT_NONE',              'MATCH_CLASS')),
(100, ('POP_JUMP_IF_TRUE',                  'POP_JUMP_IF_FALSE')),
(101, ('RAISE_VARARGS',                     'POP_JUMP_IF_NONE')),
(102, ('RERAISE',                           'POP_JUMP_IF_NOT_NONE')),
(103, ('RETURN_CONST',                      'POP_JUMP_IF_TRUE')),
(104, ('SEND',                              'RAISE_VARARGS')),
(105, ('SET_ADD',                           'RERAISE')),
(106, ('SET_FUNCTION_ATTRIBUTE',            'SEND')),
(107, ('SET_UPDATE',                        'SET_ADD')),
(108, ('STORE_ATTR',                        'SET_FUNCTION_ATTRIBUTE')),
(109, ('STORE_DEREF',                       'SET_UPDATE')),
(110, ('STORE_FAST',                        'STORE_ATTR')),
(111, ('STORE_FAST_LOAD_FAST',              'STORE_DEREF')),
(112, ('STORE_FAST_STORE_FAST',             'STORE_FAST')),
(113, ('STORE_GLOBAL',                      'STORE_FAST_LOAD_FAST')),
(114, ('STORE_NAME',                        'STORE_FAST_STORE_FAST')),
(115, ('SWAP',                              'STORE_GLOBAL')),
(116, ('UNPACK_EX',                         'STORE_NAME')),
(117, ('UNPACK_SEQUENCE',                   'SWAP')),
(118, ('YIELD_VALUE',                       'UNPACK_EX')),
(119, ('<119>',                             'UNPACK_SEQUENCE')),
(120, ('<120>',                             'YIELD_VALUE')),
(121, ('<121>',                             '<121>')),
(122, ('<122>',                             '<122>')),
(123, ('<123>',                             '<123>')),
(124, ('<124>',                             '<124>')),
(125, ('<125>',                             '<125>')),
(126, ('<126>',                             '<126>')),
(127, ('<127>',                             '<127>')),
(128, ('<128>',                             'RESUME')),
(129, ('<129>',                             'BINARY_OP_ADD_FLOAT')),
(130, ('<130>',                             'BINARY_OP_ADD_INT')),
(131, ('<131>',                             'BINARY_OP_ADD_UNICODE')),
(132, ('<132>',                             'BINARY_OP_EXTEND')),
(133, ('<133>',                             'BINARY_OP_MULTIPLY_FLOAT')),
(134, ('<134>',                             'BINARY_OP_MULTIPLY_INT')),
(135, ('<135>',                             'BINARY_OP_SUBSCR_DICT')),
(136, ('<136>',                             'BINARY_OP_SUBSCR_GETITEM')),
(137, ('<137>',                             'BINARY_OP_SUBSCR_LIST_INT')),
(138, ('<138>',                             'BINARY_OP_SUBSCR_LIST_SLICE')),
(139, ('<139>',                             'BINARY_OP_SUBSCR_STR_INT')),
(140, ('<140>',                             'BINARY_OP_SUBSCR_TUPLE_INT')),
(141, ('<141>',                             'BINARY_OP_SUBTRACT_FLOAT')),
(142, ('<142>',                             'BINARY_OP_SUBTRACT_INT')),
(143, ('<143>',                             'CALL_ALLOC_AND_ENTER_INIT')),
(144, ('<144>',                             'CALL_BOUND_METHOD_EXACT_ARGS')),
(145, ('<145>',                             'CALL_BOUND_METHOD_GENERAL')),
(146, ('<146>',                             'CALL_BUILTIN_CLASS')),
(147, ('<147>',                             'CALL_BUILTIN_FAST')),
(148, ('<148>',                             'CALL_BUILTIN_FAST_WITH_KEYWORDS')),
(149, ('RESUME',                            'CALL_BUILTIN_O')),
(150, ('<150>',                             'CALL_ISINSTANCE')),
(151, ('<151>',                             'CALL_KW_BOUND_METHOD')),
(152, ('<152>',                             'CALL_KW_NON_PY')),
(153, ('<153>',                             'CALL_KW_PY')),
(154, ('<154>',                             'CALL_LEN')),
(155, ('<155>',                             'CALL_LIST_APPEND')),
(156, ('<156>',                             'CALL_METHOD_DESCRIPTOR_FAST')),
(157, ('<157>',                             'CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS')),
(158, ('<158>',                             'CALL_METHOD_DESCRIPTOR_NOARGS')),
(159, ('<159>',                             'CALL_METHOD_DESCRIPTOR_O')),
(160, ('<160>',                             'CALL_NON_PY_GENERAL')),
(161, ('<161>',                             'CALL_PY_EXACT_ARGS')),
(162, ('<162>',                             'CALL_PY_GENERAL')),
(163, ('<163>',                             'CALL_STR_1')),
(164, ('<164>',                             'CALL_TUPLE_1')),
(165, ('<165>',                             'CALL_TYPE_1')),
(166, ('<166>',                             'COMPARE_OP_FLOAT')),
(167, ('<167>',                             'COMPARE_OP_INT')),
(168, ('<168>',                             'COMPARE_OP_STR')),
(169, ('<169>',                             'CONTAINS_OP_DICT')),
(170, ('<170>',                             'CONTAINS_OP_SET')),
(171, ('<171>',                             'FOR_ITER_GEN')),
(172, ('<172>',                             'FOR_ITER_LIST')),
(173, ('<173>',                             'FOR_ITER_RANGE')),
(174, ('<174>',                             'FOR_ITER_TUPLE')),
(175, ('<175>',                             'JUMP_BACKWARD_JIT')),
(176, ('<176>',                             'JUMP_BACKWARD_NO_JIT')),
(177, ('<177>',                             'LOAD_ATTR_CLASS')),
(178, ('<178>',                             'LOAD_ATTR_CLASS_WITH_METACLASS_CHECK')),
(179, ('<179>',                             'LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN')),
(180, ('<180>',                             'LOAD_ATTR_INSTANCE_VALUE')),
(181, ('<181>',                             'LOAD_ATTR_METHOD_LAZY_DICT')),
(182, ('<182>',                             'LOAD_ATTR_METHOD_NO_DICT')),
(183, ('<183>',                             'LOAD_ATTR_METHOD_WITH_VALUES')),
(184, ('<184>',                             'LOAD_ATTR_MODULE')),
(185, ('<185>',                             'LOAD_ATTR_NONDESCRIPTOR_NO_DICT')),
(186, ('<186>',                             'LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES')),
(187, ('<187>',                             'LOAD_ATTR_PROPERTY')),
(188, ('<188>',                             'LOAD_ATTR_SLOT')),
(189, ('<189>',                             'LOAD_ATTR_WITH_HINT')),
(190, ('<190>',                             'LOAD_CONST_IMMORTAL')),
(191, ('<191>',                             'LOAD_CONST_MORTAL')),
(192, ('<192>',                             'LOAD_GLOBAL_BUILTIN')),
(193, ('<193>',                             'LOAD_GLOBAL_MODULE')),
(194, ('<194>',                             'LOAD_SUPER_ATTR_ATTR')),
(195, ('<195>',                             'LOAD_SUPER_ATTR_METHOD')),
(196, ('<196>',                             'RESUME_CHECK')),
(197, ('<197>',                             'SEND_GEN')),
(198, ('<198>',                             'STORE_ATTR_INSTANCE_VALUE')),
(199, ('<199>',                             'STORE_ATTR_SLOT')),
(200, ('<200>',                             'STORE_ATTR_WITH_HINT')),
(201, ('<201>',                             'STORE_SUBSCR_DICT')),
(202, ('<202>',                             'STORE_SUBSCR_LIST_INT')),
(203, ('<203>',                             'TO_BOOL_ALWAYS_TRUE')),
(204, ('<204>',                             'TO_BOOL_BOOL')),
(205, ('<205>',                             'TO_BOOL_INT')),
(206, ('<206>',                             'TO_BOOL_LIST')),
(207, ('<207>',                             'TO_BOOL_NONE')),
(208, ('<208>',                             'TO_BOOL_STR')),
(209, ('<209>',                             'UNPACK_SEQUENCE_LIST')),
(210, ('<210>',                             'UNPACK_SEQUENCE_TUPLE')),
(211, ('<211>',                             'UNPACK_SEQUENCE_TWO_TUPLE')),
(212, ('<212>',                             '<212>')),
(213, ('<213>',                             '<213>')),
(214, ('<214>',                             '<214>')),
(215, ('<215>',                             '<215>')),
(216, ('<216>',                             '<216>')),
(217, ('<217>',                             '<217>')),
(218, ('<218>',                             '<218>')),
(219, ('<219>',                             '<219>')),
(220, ('<220>',                             '<220>')),
(221, ('<221>',                             '<221>')),
(222, ('<222>',                             '<222>')),
(223, ('<223>',                             '<223>')),
(224, ('<224>',                             '<224>')),
(225, ('<225>',                             '<225>')),
(226, ('<226>',                             '<226>')),
(227, ('<227>',                             '<227>')),
(228, ('<228>',                             '<228>')),
(229, ('<229>',                             '<229>')),
(230, ('<230>',                             '<230>')),
(231, ('<231>',                             '<231>')),
(232, ('<232>',                             '<232>')),
(233, ('<233>',                             '<233>')),
(234, ('<234>',                             'INSTRUMENTED_END_FOR')),
(235, ('<235>',                             'INSTRUMENTED_POP_ITER')),
(236, ('INSTRUMENTED_RESUME',               'INSTRUMENTED_END_SEND')),
(237, ('INSTRUMENTED_END_FOR',              'INSTRUMENTED_FOR_ITER')),
(238, ('INSTRUMENTED_END_SEND',             'INSTRUMENTED_INSTRUCTION')),
(239, ('INSTRUMENTED_RETURN_VALUE',         'INSTRUMENTED_JUMP_FORWARD')),
(240, ('INSTRUMENTED_RETURN_CONST',         'INSTRUMENTED_NOT_TAKEN')),
(241, ('INSTRUMENTED_YIELD_VALUE',          'INSTRUMENTED_POP_JUMP_IF_TRUE')),
(242, ('INSTRUMENTED_LOAD_SUPER_ATTR',      'INSTRUMENTED_POP_JUMP_IF_FALSE')),
(243, ('INSTRUMENTED_FOR_ITER',             'INSTRUMENTED_POP_JUMP_IF_NONE')),
(244, ('INSTRUMENTED_CALL',                 'INSTRUMENTED_POP_JUMP_IF_NOT_NONE')),
(245, ('INSTRUMENTED_CALL_KW',              'INSTRUMENTED_RESUME')),
(246, ('INSTRUMENTED_CALL_FUNCTION_EX',     'INSTRUMENTED_RETURN_VALUE')),
(247, ('INSTRUMENTED_INSTRUCTION',          'INSTRUMENTED_YIELD_VALUE')),
(248, ('INSTRUMENTED_JUMP_FORWARD',         'INSTRUMENTED_END_ASYNC_FOR')),
(249, ('INSTRUMENTED_JUMP_BACKWARD',        'INSTRUMENTED_LOAD_SUPER_ATTR')),
(250, ('INSTRUMENTED_POP_JUMP_IF_TRUE',     'INSTRUMENTED_CALL')),
(251, ('INSTRUMENTED_POP_JUMP_IF_FALSE',    'INSTRUMENTED_CALL_KW')),
(252, ('INSTRUMENTED_POP_JUMP_IF_NONE',     'INSTRUMENTED_CALL_FUNCTION_EX')),
(253, ('INSTRUMENTED_POP_JUMP_IF_NOT_NONE', 'INSTRUMENTED_JUMP_BACKWARD')),
(254, ('INSTRUMENTED_LINE',                 'INSTRUMENTED_LINE')),
(255, ('<255>',                             'ENTER_EXECUTOR')),
(256, ('JUMP',                              'ANNOTATIONS_PLACEHOLDER')),
(257, ('JUMP_NO_INTERRUPT',                 'JUMP')),
(258, ('LOAD_CLOSURE',                      'JUMP_IF_FALSE')),
(259, ('LOAD_METHOD',                       'JUMP_IF_TRUE')),
(260, ('LOAD_SUPER_METHOD',                 'JUMP_NO_INTERRUPT')),
(261, ('LOAD_ZERO_SUPER_ATTR',              'LOAD_CLOSURE')),
(262, ('LOAD_ZERO_SUPER_METHOD',            'POP_BLOCK')),
(263, ('POP_BLOCK',                         'SETUP_CLEANUP')),
(264, ('SETUP_CLEANUP',                     'SETUP_FINALLY')),
(265, ('SETUP_FINALLY',                     'SETUP_WITH')),
(266, ('SETUP_WITH',                        'STORE_FAST_MAYBE_NULL')),
(267, ('STORE_FAST_MAYBE_NULL',             'empty'))

# 3.13
CACHE', 'BEFORE_ASYNC_WITH', 'BEFORE_WITH', '<3>', 'BINARY_SLICE', 'BINARY_SUBSCR', 'CHECK_EG_MATCH', 'CHECK_EXC_MATCH', 'CLEANUP_THROW', 'DELETE_SUBSCR', 'END_ASYNC_FOR', 'END_FOR', 'END_SEND', 'EXIT_INIT_CHECK', 'FORMAT_SIMPLE', 'FORMAT_WITH_SPEC', 'GET_AITER', 'RESERVED', 'GET_ANEXT', 'GET_ITER', 'GET_LEN', 'GET_YIELD_FROM_ITER', 'INTERPRETER_EXIT', 'LOAD_ASSERTION_ERROR', 'LOAD_BUILD_CLASS', 'LOAD_LOCALS', 'MAKE_FUNCTION', 'MATCH_KEYS', 'MATCH_MAPPING', 'MATCH_SEQUENCE', 'NOP', 'POP_EXCEPT', 'POP_TOP', 'PUSH_EXC_INFO', 'PUSH_NULL', 'RETURN_GENERATOR', 'RETURN_VALUE', 'SETUP_ANNOTATIONS', 'STORE_SLICE', 'STORE_SUBSCR', 'TO_BOOL', 'UNARY_INVERT', 'UNARY_NEGATIVE', 'UNARY_NOT', 'WITH_EXCEPT_START', 'BINARY_OP', 'BUILD_CONST_KEY_MAP', 'BUILD_LIST', 'BUILD_MAP', 'BUILD_SET', 'BUILD_SLICE', 'BUILD_STRING', 'BUILD_TUPLE', 'CALL', 'CALL_FUNCTION_EX', 'CALL_INTRINSIC_1', 'CALL_INTRINSIC_2', 'CALL_KW', 'COMPARE_OP', 'CONTAINS_OP', 'CONVERT_VALUE', 'COPY', 'COPY_FREE_VARS', 'DELETE_ATTR', 'DELETE_DEREF', 'DELETE_FAST', 'DELETE_GLOBAL', 'DELETE_NAME', 'DICT_MERGE', 'DICT_UPDATE', 'ENTER_EXECUTOR', 'EXTENDED_ARG', 'FOR_ITER', 'GET_AWAITABLE', 'IMPORT_FROM', 'IMPORT_NAME', 'IS_OP', 'JUMP_BACKWARD', 'JUMP_BACKWARD_NO_INTERRUPT', 'JUMP_FORWARD', 'LIST_APPEND', 'LIST_EXTEND', 'LOAD_ATTR', 'LOAD_CONST', 'LOAD_DEREF', 'LOAD_FAST', 'LOAD_FAST_AND_CLEAR', 'LOAD_FAST_CHECK', 'LOAD_FAST_LOAD_FAST', 'LOAD_FROM_DICT_OR_DEREF', 'LOAD_FROM_DICT_OR_GLOBALS', 'LOAD_GLOBAL', 'LOAD_NAME', 'LOAD_SUPER_ATTR', 'MAKE_CELL', 'MAP_ADD', 'MATCH_CLASS', 'POP_JUMP_IF_FALSE', 'POP_JUMP_IF_NONE', 'POP_JUMP_IF_NOT_NONE', 'POP_JUMP_IF_TRUE', 'RAISE_VARARGS', 'RERAISE', 'RETURN_CONST', 'SEND', 'SET_ADD', 'SET_FUNCTION_ATTRIBUTE', 'SET_UPDATE', 'STORE_ATTR', 'STORE_DEREF', 'STORE_FAST', 'STORE_FAST_LOAD_FAST', 'STORE_FAST_STORE_FAST', 'STORE_GLOBAL', 'STORE_NAME', 'SWAP', 'UNPACK_EX', 'UNPACK_SEQUENCE', 'YIELD_VALUE', '<119>', '<120>', '<121>', '<122>', '<123>', '<124>', '<125>', '<126>', '<127>', '<128>', '<129>', '<130>', '<131>', '<132>', '<133>', '<134>', '<135>', '<136>', '<137>', '<138>', '<139>', '<140>', '<141>', '<142>', '<143>', '<144>', '<145>', '<146>', '<147>', '<148>', 'RESUME', '<150>', '<151>', '<152>', '<153>', '<154>', '<155>', '<156>', '<157>', '<158>', '<159>', '<160>', '<161>', '<162>', '<163>', '<164>', '<165>', '<166>', '<167>', '<168>', '<169>', '<170>', '<171>', '<172>', '<173>', '<174>', '<175>', '<176>', '<177>', '<178>', '<179>', '<180>', '<181>', '<182>', '<183>', '<184>', '<185>', '<186>', '<187>', '<188>', '<189>', '<190>', '<191>', '<192>', '<193>', '<194>', '<195>', '<196>', '<197>', '<198>', '<199>', '<200>', '<201>', '<202>', '<203>', '<204>', '<205>', '<206>', '<207>', '<208>', '<209>', '<210>', '<211>', '<212>', '<213>', '<214>', '<215>', '<216>', '<217>', '<218>', '<219>', '<220>', '<221>', '<222>', '<223>', '<224>', '<225>', '<226>', '<227>', '<228>', '<229>', '<230>', '<231>', '<232>', '<233>', '<234>', '<235>', 'INSTRUMENTED_RESUME', 'INSTRUMENTED_END_FOR', 'INSTRUMENTED_END_SEND', 'INSTRUMENTED_RETURN_VALUE', 'INSTRUMENTED_RETURN_CONST', 'INSTRUMENTED_YIELD_VALUE', 'INSTRUMENTED_LOAD_SUPER_ATTR', 'INSTRUMENTED_FOR_ITER', 'INSTRUMENTED_CALL', 'INSTRUMENTED_CALL_KW', 'INSTRUMENTED_CALL_FUNCTION_EX', 'INSTRUMENTED_INSTRUCTION', 'INSTRUMENTED_JUMP_FORWARD', 'INSTRUMENTED_JUMP_BACKWARD', 'INSTRUMENTED_POP_JUMP_IF_TRUE', 'INSTRUMENTED_POP_JUMP_IF_FALSE', 'INSTRUMENTED_POP_JUMP_IF_NONE', 'INSTRUMENTED_POP_JUMP_IF_NOT_NONE', 'INSTRUMENTED_LINE', '<255>', 'JUMP', 'JUMP_NO_INTERRUPT', 'LOAD_CLOSURE', 'LOAD_METHOD', 'LOAD_SUPER_METHOD', 'LOAD_ZERO_SUPER_ATTR', 'LOAD_ZERO_SUPER_METHOD', 'POP_BLOCK', 'SETUP_CLEANUP', 'SETUP_FINALLY', 'SETUP_WITH', 'STORE_FAST_MAYBE_NULL'

# 3.14
'CACHE', 'BINARY_SLICE', 'BUILD_TEMPLATE', 'BINARY_OP_INPLACE_ADD_UNICODE', 'CALL_FUNCTION_EX', 'CHECK_EG_MATCH', 'CHECK_EXC_MATCH', 'CLEANUP_THROW', 'DELETE_SUBSCR', 'END_FOR', 'END_SEND', 'EXIT_INIT_CHECK', 'FORMAT_SIMPLE', 'FORMAT_WITH_SPEC', 'GET_AITER', 'GET_ANEXT', 'GET_ITER', 'RESERVED', 'GET_LEN', 'GET_YIELD_FROM_ITER', 'INTERPRETER_EXIT', 'LOAD_BUILD_CLASS', 'LOAD_LOCALS', 'MAKE_FUNCTION', 'MATCH_KEYS', 'MATCH_MAPPING', 'MATCH_SEQUENCE', 'NOP', 'NOT_TAKEN', 'POP_EXCEPT', 'POP_ITER', 'POP_TOP', 'PUSH_EXC_INFO', 'PUSH_NULL', 'RETURN_GENERATOR', 'RETURN_VALUE', 'SETUP_ANNOTATIONS', 'STORE_SLICE', 'STORE_SUBSCR', 'TO_BOOL', 'UNARY_INVERT', 'UNARY_NEGATIVE', 'UNARY_NOT', 'WITH_EXCEPT_START', 'BINARY_OP', 'BUILD_INTERPOLATION', 'BUILD_LIST', 'BUILD_MAP', 'BUILD_SET', 'BUILD_SLICE', 'BUILD_STRING', 'BUILD_TUPLE', 'CALL', 'CALL_INTRINSIC_1', 'CALL_INTRINSIC_2', 'CALL_KW', 'COMPARE_OP', 'CONTAINS_OP', 'CONVERT_VALUE', 'COPY', 'COPY_FREE_VARS', 'DELETE_ATTR', 'DELETE_DEREF', 'DELETE_FAST', 'DELETE_GLOBAL', 'DELETE_NAME', 'DICT_MERGE', 'DICT_UPDATE', 'END_ASYNC_FOR', 'EXTENDED_ARG', 'FOR_ITER', 'GET_AWAITABLE', 'IMPORT_FROM', 'IMPORT_NAME', 'IS_OP', 'JUMP_BACKWARD', 'JUMP_BACKWARD_NO_INTERRUPT', 'JUMP_FORWARD', 'LIST_APPEND', 'LIST_EXTEND', 'LOAD_ATTR', 'LOAD_COMMON_CONSTANT', 'LOAD_CONST', 'LOAD_DEREF', 'LOAD_FAST', 'LOAD_FAST_AND_CLEAR', 'LOAD_FAST_BORROW', 'LOAD_FAST_BORROW_LOAD_FAST_BORROW', 'LOAD_FAST_CHECK', 'LOAD_FAST_LOAD_FAST', 'LOAD_FROM_DICT_OR_DEREF', 'LOAD_FROM_DICT_OR_GLOBALS', 'LOAD_GLOBAL', 'LOAD_NAME', 'LOAD_SMALL_INT', 'LOAD_SPECIAL', 'LOAD_SUPER_ATTR', 'MAKE_CELL', 'MAP_ADD', 'MATCH_CLASS', 'POP_JUMP_IF_FALSE', 'POP_JUMP_IF_NONE', 'POP_JUMP_IF_NOT_NONE', 'POP_JUMP_IF_TRUE', 'RAISE_VARARGS', 'RERAISE', 'SEND', 'SET_ADD', 'SET_FUNCTION_ATTRIBUTE', 'SET_UPDATE', 'STORE_ATTR', 'STORE_DEREF', 'STORE_FAST', 'STORE_FAST_LOAD_FAST', 'STORE_FAST_STORE_FAST', 'STORE_GLOBAL', 'STORE_NAME', 'SWAP', 'UNPACK_EX', 'UNPACK_SEQUENCE', 'YIELD_VALUE', '<121>', '<122>', '<123>', '<124>', '<125>', '<126>', '<127>', 'RESUME', 'BINARY_OP_ADD_FLOAT', 'BINARY_OP_ADD_INT', 'BINARY_OP_ADD_UNICODE', 'BINARY_OP_EXTEND', 'BINARY_OP_MULTIPLY_FLOAT', 'BINARY_OP_MULTIPLY_INT', 'BINARY_OP_SUBSCR_DICT', 'BINARY_OP_SUBSCR_GETITEM', 'BINARY_OP_SUBSCR_LIST_INT', 'BINARY_OP_SUBSCR_LIST_SLICE', 'BINARY_OP_SUBSCR_STR_INT', 'BINARY_OP_SUBSCR_TUPLE_INT', 'BINARY_OP_SUBTRACT_FLOAT', 'BINARY_OP_SUBTRACT_INT', 'CALL_ALLOC_AND_ENTER_INIT', 'CALL_BOUND_METHOD_EXACT_ARGS', 'CALL_BOUND_METHOD_GENERAL', 'CALL_BUILTIN_CLASS', 'CALL_BUILTIN_FAST', 'CALL_BUILTIN_FAST_WITH_KEYWORDS', 'CALL_BUILTIN_O', 'CALL_ISINSTANCE', 'CALL_KW_BOUND_METHOD', 'CALL_KW_NON_PY', 'CALL_KW_PY', 'CALL_LEN', 'CALL_LIST_APPEND', 'CALL_METHOD_DESCRIPTOR_FAST', 'CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS', 'CALL_METHOD_DESCRIPTOR_NOARGS', 'CALL_METHOD_DESCRIPTOR_O', 'CALL_NON_PY_GENERAL', 'CALL_PY_EXACT_ARGS', 'CALL_PY_GENERAL', 'CALL_STR_1', 'CALL_TUPLE_1', 'CALL_TYPE_1', 'COMPARE_OP_FLOAT', 'COMPARE_OP_INT', 'COMPARE_OP_STR', 'CONTAINS_OP_DICT', 'CONTAINS_OP_SET', 'FOR_ITER_GEN', 'FOR_ITER_LIST', 'FOR_ITER_RANGE', 'FOR_ITER_TUPLE', 'JUMP_BACKWARD_JIT', 'JUMP_BACKWARD_NO_JIT', 'LOAD_ATTR_CLASS', 'LOAD_ATTR_CLASS_WITH_METACLASS_CHECK', 'LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN', 'LOAD_ATTR_INSTANCE_VALUE', 'LOAD_ATTR_METHOD_LAZY_DICT', 'LOAD_ATTR_METHOD_NO_DICT', 'LOAD_ATTR_METHOD_WITH_VALUES', 'LOAD_ATTR_MODULE', 'LOAD_ATTR_NONDESCRIPTOR_NO_DICT', 'LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES', 'LOAD_ATTR_PROPERTY', 'LOAD_ATTR_SLOT', 'LOAD_ATTR_WITH_HINT', 'LOAD_CONST_IMMORTAL', 'LOAD_CONST_MORTAL', 'LOAD_GLOBAL_BUILTIN', 'LOAD_GLOBAL_MODULE', 'LOAD_SUPER_ATTR_ATTR', 'LOAD_SUPER_ATTR_METHOD', 'RESUME_CHECK', 'SEND_GEN', 'STORE_ATTR_INSTANCE_VALUE', 'STORE_ATTR_SLOT', 'STORE_ATTR_WITH_HINT', 'STORE_SUBSCR_DICT', 'STORE_SUBSCR_LIST_INT', 'TO_BOOL_ALWAYS_TRUE', 'TO_BOOL_BOOL', 'TO_BOOL_INT', 'TO_BOOL_LIST', 'TO_BOOL_NONE', 'TO_BOOL_STR', 'UNPACK_SEQUENCE_LIST', 'UNPACK_SEQUENCE_TUPLE', 'UNPACK_SEQUENCE_TWO_TUPLE', '<212>', '<213>', '<214>', '<215>', '<216>', '<217>', '<218>', '<219>', '<220>', '<221>', '<222>', '<223>', '<224>', '<225>', '<226>', '<227>', '<228>', '<229>', '<230>', '<231>', '<232>', '<233>', 'INSTRUMENTED_END_FOR', 'INSTRUMENTED_POP_ITER', 'INSTRUMENTED_END_SEND', 'INSTRUMENTED_FOR_ITER', 'INSTRUMENTED_INSTRUCTION', 'INSTRUMENTED_JUMP_FORWARD', 'INSTRUMENTED_NOT_TAKEN', 'INSTRUMENTED_POP_JUMP_IF_TRUE', 'INSTRUMENTED_POP_JUMP_IF_FALSE', 'INSTRUMENTED_POP_JUMP_IF_NONE', 'INSTRUMENTED_POP_JUMP_IF_NOT_NONE', 'INSTRUMENTED_RESUME', 'INSTRUMENTED_RETURN_VALUE', 'INSTRUMENTED_YIELD_VALUE', 'INSTRUMENTED_END_ASYNC_FOR', 'INSTRUMENTED_LOAD_SUPER_ATTR', 'INSTRUMENTED_CALL', 'INSTRUMENTED_CALL_KW', 'INSTRUMENTED_CALL_FUNCTION_EX', 'INSTRUMENTED_JUMP_BACKWARD', 'INSTRUMENTED_LINE', 'ENTER_EXECUTOR', 'ANNOTATIONS_PLACEHOLDER', 'JUMP', 'JUMP_IF_FALSE', 'JUMP_IF_TRUE', 'JUMP_NO_INTERRUPT', 'LOAD_CLOSURE', 'POP_BLOCK', 'SETUP_CLEANUP', 'SETUP_FINALLY', 'SETUP_WITH', 'STORE_FAST_MAYBE_NULL'
"""

#            OP NAME OPCODE POP PUSH
# ---------------------------------------------------------------
# def_op(loc,  "",      )


update_pj3(globals(), loc)
finalize_opcodes(loc)
